# in the templates via {{ site.myvariable }}.
title: Le comptoir des bois du 83
subtitle: Bois de coutellerie, tournage et bijouterie.
email: admin@bois.fr
description: >- # this means to ignore newlines until "baseurl:"
  Bois de coutellerie, tournage & bijouterie en plaquettes, quillons & carrelets.  
  Bois bruts, stabilisés, hybrides et créations. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lecomptoirdesboisdu83.fr" # the base hostname & protocol for your site, e.g. http://example.com
encoding: "utf-8"
timezone: Europe/Paris
fb-url: https://www.facebook.com/dubois/
ig-url: https://www.facebook.com/dubois/

# Gems et extensions
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
exclude:
- Dockerfile
- Dockerfile.dev
- nginx.conf

collections_dir: produits
collections:
  essences:
    output: true
    permalink: /essences/:title
  hybrides:
    output: true
    permalink: /hybrides/:title

defaults:
  -
    scope:
      path: "produits/*/*" # an empty string here means all files in the project
    values:
      layout: "post"

sass:
  sass_dir: css
  style: compressed

manifest_name: Le comptoir des bois du 83
manifest_short_name: Comptoir83 # Appears in "Add to home screen" dialogues and may have other importance also
manifest_lang: fr
manifest_background_color: white
manifest_display: standalone

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
