backend:
  name: github
  repo: romarr/bois # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://rsoauth.herokuapp.com

media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "essences"
    label: "Essences"
    folder: "produits/_essences"
    create: true
    slug: "{{day}}-{{second}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "sku", widget: "string"}
      - {label: "Prix", name: "prix", widget: "number"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Région", name: "region", widget: "string"}
      - label: "Photo"
        name: "image"
        widget: "list"
        fields:
          - {label: Texte, name: alt, widget: string}
          - {label: Photo, name: photo, widget: image}
      - {label: "Poids", name: "poids", widget: "number"}
      - {label: "Texte", name: "body", widget: "markdown"}

  - name: "prestations"
    label: "Prestations"
    folder: "produits/_prestations"
    create: true
    slug: "{{day}}-{{second}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "sku", widget: "string"}
      - {label: "Prix", name: "price", widget: "number"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Type", name: "type", widget: "list"}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Texte", name: "body", widget: "markdown"}

  - name: "realisations"
    label: "Réalisations"
    folder: "produits/_realisations"
    create: true
    slug: "{{day}}-{{second}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "sku", widget: "string"}
      - {label: "Prix", name: "price", widget: "number"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Région", name: "region", widget: "string"}
      - {label: "Tons", name: "tons", widget: "list"}
      - {label: "Variantes", name: "variantes", widget: "list"}
      - label: "Photo"
        name: "image"
        widget: "list"
        fields:
          - {label: Texte, name: alt, widget: string}
          - {label: Photo, name: photo, widget: image}
      - {label: "Poids", name: "poids", widget: "number"}
      - {label: "Texte", name: "body", widget: "markdown"}