backend:
  name: github
  repo: romarr/bois # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://rsoauth.herokuapp.com

media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "essences"
    label: "Essences"
    folder: "produits/_essences"
    create: true
    slug: "{{day}}-{{second}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "string", default: "post"}
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "gid", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Région", name: "region", widget: "select", options: ["europe", "amériques", "asie", "océanie", "afrique"]}
      - {label: "Détails", name: "details", widget: "text"}
      - {label: "Couleurs", name: "couleur", widget: "list", required: false}
      - {label: "Densité", name: "densite", widget: "string", required: false}
      - {label: "Veines", name: "veines", widget: "select", options: ["Avec", "Sans"]}
      - {label: "Rareté", required: false, name: "rarete", widget: "select", options: ["Précieux", "Exotique", "Ronce", "Loupe"], multiple: true}
      - label: "Produits"
        required: false
        name: "produits"
        widget: "list"
        fields:
          - {label: "Id produit", name: "pid", widget: "string"}
          - {label: "Type", name: "type", widget: "select", options: ["Bloc", "Carrelet", "Plaquette"]}
          - {label: "Photos", name: "photos", widget: "list", field: {label: Photo, name: photo, widget: image}}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Dimensions", name: "dimensions", widget: "string"}
          - {label: "Poids", name: "poids", widget: "number"}
          - {label: "Prix", name: "prix", widget: "string", required: false}

  - name: "hybrides"
    label: "Hybrides"
    folder: "produits/_hybrides"
    create: true
    slug: "{{day}}-{{second}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "string", default: "post"}
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "gid", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Région", name: "region", widget: "select", options: ["europe", "amériques", "asie", "océanie", "afrique"]}
      - {label: "Détails", name: "details", widget: "text"}
      - {label: "Couleurs", name: "couleur", widget: "list", required: false}
      - {label: "Densité", name: "densite", widget: "string", required: false}
      - {label: "Veines", name: "veines", widget: "select", options: ["Avec", "Sans"]}
      - {label: "Rareté", required: false, name: "rarete", widget: "select", options: ["Précieux", "Exotique", "Ronce", "Loupe"], multiple: true}
      - label: "Produits"
        required: false
        name: "produits"
        widget: "list"
        fields:
          - {label: "Id produit", name: "pid", widget: "string"}
          - {label: "Type", name: "type", widget: "select", options: ["Bloc", "Carrelet", "Plaquette"]}
          - {label: "Photos", name: "photos", widget: "list", field: {label: Photo, name: photo, widget: image}}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Dimensions", name: "dimensions", widget: "string"}
          - {label: "Poids", name: "poids", widget: "number"}
          - {label: "Prix", name: "prix", widget: "string", required: false}

  - label: "Global"
    name: "global"
    files:
      - label: "Business Info"
        name: "info"
        file: "_data/business.yml"
        fields:
          - {label: name, name: name, widget: string}
          - {label: address_full, name: address_full, widget: string, hint: "Example: 333 S. Franklin Street Tampa, FL 33602"}
          - {label: address_street, name: address_street, widget: string, hint: "Example: 333 S. Franklin Street"}
          - {label: address_city, name: address_city, widget: string, hint: "Tampa"}
          - {label: phone_primay, name: phone_primay, widget: string, pattern: ['[(]?\d{3}[-.)]?[ ]?\d{3}[-.]?\d{4}\b', "Must be a phone number"], hint: "(813) 123-4567"}
          - {label: phone_secondary, name: phone_secondary, widget: string, hint: "(813) 765-4321"}
          - {label: fax, name: fax, widget: string, hint: "(813) 666-6666"}
          - {label: email_primary, name: email_primary, widget: string, pattern: ['([\w\.\-_]+)?\w+@[\w-_]+(\.\w+){1,}', "Must be an email address"]}
          - {label: google_maps_api_key, name: google_maps_api_key, widget: string, hint: "Used to display embeded maps"}