backend:
  name: github
  repo: romarr/bois # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://rsoauth.herokuapp.com

media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "essences"
    label: "Essences"
    folder: "produits/_essences"
    create: true
    slug: "{{day}}-{{second}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "string", default: "post"}
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "gid", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Région", name: "region", widget: "select", options: ["europe", "amériques", "asie", "océanie", "afrique"]}
      - {label: "Détails", name: "details", widget: "text"}
      - {label: "Couleurs", name: "couleur", widget: "list", required: false}
      - {label: "Densité", name: "densite", widget: "string", required: false}
      - {label: "Veines", name: "veines", widget: "select", options: ["Avec", "Sans"]}
      - {label: "Rareté", required: false, name: "rarete", widget: "select", options: ["Précieux", "Exotique", "Ronce", "Loupe"], multiple: true}
      - label: "Produits"
        required: false
        name: "produits"
        widget: "list"
        fields:
          - {label: "Id produit", name: "pid", widget: "string"}
          - {label: "Type", name: "type", widget: "select", options: ["Bloc", "Carrelet", "Plaquette"]}
          - {label: "Photos", name: "photos", widget: "list", field: {label: Photo, name: photo, widget: image}}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Dimensions", name: "dimensions", widget: "string"}
          - {label: "Poids", name: "poids", widget: "number"}
          - {label: "Prix", name: "prix", widget: "number"}

  - name: "hybrides"
    label: "Hybrides"
    folder: "produits/hybrides"
    create: true
    slug: "{{day}}-{{second}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "string", default: "post"}
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "gid", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Région", name: "region", widget: "select", options: ["europe", "amériques", "asie", "océanie", "afrique"]}
      - {label: "Détails", name: "details", widget: "text"}
      - {label: "Couleurs", name: "couleur", widget: "list", required: false}
      - {label: "Densité", name: "densite", widget: "string", required: false}
      - {label: "Veines", name: "veines", widget: "select", options: ["Avec", "Sans"]}
      - {label: "Rareté", required: false, name: "rarete", widget: "select", options: ["Précieux", "Exotique", "Ronce", "Loupe"], multiple: true}
      - label: "Produits"
        required: false
        name: "produits"
        widget: "list"
        fields:
          - {label: "Id produit", name: "pid", widget: "string"}
          - {label: "Type", name: "type", widget: "select", options: ["Bloc", "Carrelet", "Plaquette"]}
          - {label: "Photos", name: "photos", widget: "list", field: {label: Photo, name: photo, widget: image}}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Dimensions", name: "dimensions", widget: "string"}
          - {label: "Poids", name: "poids", widget: "number"}
          - {label: "Prix", name: "prix", widget: "number"}